### ISSUE TITLE
Links do not exist 

### ISSUE THREAD

**Issue by networkprogrammer** [common-fate/docs#118]
The url linked at line 90 on this page returns a 404
https://github.com/common-fate/docs/blob/main/docs/granted/usage/console.md?plain=1#L90 

The url points to
https://github.com/common-fate/granted/blob/main/pkg/browsers/console.go

**Comment by chrnorm** [comment]
Thanks for reporting this issue @networkprogrammer! I've added a PR in #120 which will fix this up.
